# Generated by Django 2.2.24 on 2024-05-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('program', 'code', 'year', 'semester')},
        ),
    ]
