# Generated by Django 2.2.24 on 2024-06-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20240523_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
