# Generated by Django 2.2.24 on 2024-06-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20240615_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='abbreviation',
            field=models.CharField(default='DEFAULT', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('program', 'code', 'abbreviation', 'year', 'semester')},
        ),
    ]
