# Generated by Django 2.2.24 on 2024-08-01 20:56

from django.db import migrations, models
import django.db.models.deletion
import json

def get_data_from_file():
    import os
    current_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(current_dir, 'data', 'dataLoadEducationalProducts.json')

    with open(json_path, encoding='utf-8') as file:
        return(json.load(file))

def load_data(apps, schema_editor):
    EducationalType = apps.get_model('survey', 'EducationalType')
    EducationalProduct = apps.get_model('survey', 'EducationalProduct')
    StudyOption = apps.get_model('survey', 'StudyOption')
    Study = apps.get_model('survey', 'Study')

    # Path to the JSON file

    data = get_data_from_file()

    # Load EducationalType data
    for et_data in data['educational_types']:
        et = EducationalType.objects.create(
            code=et_data['code'],
            name=et_data['name'],
            description=et_data['description'],
        )
        et.styles.set(StudyOption.objects.filter(code__in=et_data['styles']))
        et.intelligences.set(StudyOption.objects.filter(code__in=et_data['intelligences']))
        et.save()

    # Load EducationalProduct data
    for ep_data in data['educational_products']:
        ep = EducationalProduct.objects.create(
            name=ep_data['name'],
            info=ep_data['info'],
            link=ep_data['link'],
            type=EducationalType.objects.get(code=ep_data['type'])
        )
        ep.styles.set(StudyOption.objects.filter(code__in=ep_data['styles']))
        ep.intelligences.set(StudyOption.objects.filter(code__in=ep_data['intelligences']))
        ep.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20240623_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('intelligences', models.ManyToManyField(related_name='intelligences', to='survey.StudyOption')),
                ('styles', models.ManyToManyField(related_name='styles', to='survey.StudyOption')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('intelligences', models.ManyToManyField(related_name='intelligences_products', to='survey.StudyOption')),
                ('styles', models.ManyToManyField(related_name='styles_products', to='survey.StudyOption')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_type', to='survey.EducationalType')),
            ],
        ),
        migrations.RunPython(load_data),
    ]
