# Generated by Django 2.2.24 on 2024-08-18 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_educationalproduct_educationaltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Positive'), (0, 'Negative')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_ratings', to='survey.EducationalProduct')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_ratings', to='survey.Student')),
            ],
            options={
                'unique_together': {('student', 'product')},
            },
        ),
    ]
