# Generated by Django 2.2.24 on 2024-08-28 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_productrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_recommendations', to='survey.Class')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_recommendations', to='survey.EducationalProduct')),
            ],
            options={
                'unique_together': {('product', 'class_id')},
            },
        ),
    ]
