# Generated by Django 2.2.24 on 2024-09-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_professorrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMethodology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('intelligences', models.ManyToManyField(related_name='intelligences_methodologies', to='survey.StudyOption')),
                ('styles', models.ManyToManyField(related_name='styles_methodologies', to='survey.StudyOption')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='methodologies_type', to='survey.EducationalType')),
            ],
        ),
    ]
