# Generated by Django 2.2.24 on 2024-09-08 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_learningmethodology'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('intelligences', models.ManyToManyField(related_name='learning_intelligences', to='survey.StudyOption')),
                ('styles', models.ManyToManyField(related_name='learning_styles', to='survey.StudyOption')),
            ],
        ),
        migrations.AlterField(
            model_name='learningmethodology',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='methodologies_type', to='survey.LearningType'),
        ),
    ]
