# Generated by Django 2.2.24 on 2024-12-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favorite_products', to='survey.EducationalProduct')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favorite_students', to='survey.Student')),
            ],
            options={
                'unique_together': {('student', 'product')},
            },
        ),
    ]
