# Generated by Django 2.2.24 on 2025-03-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_favoriteproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalproduct',
            name='activity_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='educationalproduct',
            name='content_source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='educationalproduct',
            name='media_format',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='educationalproduct',
            name='educational_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
