# Generated by Django 2.2.24 on 2025-03-18 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_add_fields_to_educational_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_products', to='survey.Class')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='survey.EducationalProduct')),
            ],
            options={
                'unique_together': {('class_id', 'product')},
            },
        ),
    ]
