# Generated by Django 2.2.24 on 2026-02-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_classproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalproduct',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationalproduct',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Aprovado'), ('PENDING', 'Pendente'), ('REJECTED', 'Rejeitado')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='educationalproduct',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_products', to='survey.Professor'),
        ),
    ]
