# Generated by Django 2.2.24 on 2026-02-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20260203_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalproduct',
            name='suggested_for_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_suggestions', to='survey.Class'),
        ),
    ]
